# Generated by Django 4.1.5 on 2023-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Board', '0002_message_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
